name: Build Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update build
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Move distribution files to dist folder
        run: |
          mv dist/* dist/