name: Build Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update build
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Commit new distribution files to repo
        uses: stefanzweifel/git-auto-commit-action@v5